"""The 67 Pennsylvania counties. FIPS codes are the odd numbers 001 to 133 in
alphabetical order of county name. Used to cross-check geometry and population files."""

NAMES = [
    "Adams",
    "Allegheny",
    "Armstrong",
    "Beaver",
    "Bedford",
    "Berks",
    "Blair",
    "Bradford",
    "Bucks",
    "Butler",
    "Cambria",
    "Cameron",
    "Carbon",
    "Centre",
    "Chester",
    "Clarion",
    "Clearfield",
    "Clinton",
    "Columbia",
    "Crawford",
    "Cumberland",
    "Dauphin",
    "Delaware",
    "Elk",
    "Erie",
    "Fayette",
    "Forest",
    "Franklin",
    "Fulton",
    "Greene",
    "Huntingdon",
    "Indiana",
    "Jefferson",
    "Juniata",
    "Lackawanna",
    "Lancaster",
    "Lawrence",
    "Lebanon",
    "Lehigh",
    "Luzerne",
    "Lycoming",
    "McKean",
    "Mercer",
    "Mifflin",
    "Monroe",
    "Montgomery",
    "Montour",
    "Northampton",
    "Northumberland",
    "Perry",
    "Philadelphia",
    "Pike",
    "Potter",
    "Schuylkill",
    "Snyder",
    "Somerset",
    "Sullivan",
    "Susquehanna",
    "Tioga",
    "Union",
    "Venango",
    "Warren",
    "Washington",
    "Wayne",
    "Westmoreland",
    "Wyoming",
    "York",
]

COUNTIES: dict[str, str] = {f"42{2 * i + 1:03d}": n for i, n in enumerate(NAMES)}

assert len(COUNTIES) == 67
